### ISSUE TITLE
Definition for rule(s) was not found

### ISSUE THREAD

**Issue by FabianElezi** [paulschoen/eslint-plugin-zustand-rules#2]
I have configured the plugin exactly like described and I am getting the following warnings:

- ESLint: Definition for rule 'zustand-rules/enforce-slices-when-large-state' was not found. (zustand-rules/enforce-slices-when-large-state)
- ESLint: Definition for rule 'zustand-rules/enforce-state-before-actions' was not found. (zustand-rules/enforce-state-before-actions)
- ESLint: Definition for rule 'zustand-rules/enforce-use-setstate' was not found. (zustand-rules/enforce-use-setstate)
- ESLint: Definition for rule 'zustand-rules/no-state-mutation' was not found. (zustand-rules/no-state-mutation)
- ESLint: Definition for rule 'zustand-rules/use-store-selectors' was not found. (zustand-rules/use-store-selectors)

For some reason it can't find the rules. I tried restarting the IDE (Webstorm) but the problem persists.

p.s. I have many other plugins and rules already implemented so I doubt this is a configuration issue.

<img width="923" alt="Image" src="https://github.com/user-attachments/assets/b09f6258-4bf0-45de-928b-9a4fa057ccc1" />

**Comment by silverwind** [comment]
Having the same issue. I'm trying to use this plugin with a `.eslintrc.yaml` like this:

```yaml
plugins:
  - zustand-rules

rules:
  zustand-rules/no-multiple-stores: [0]
  zustand-rules/use-store-selectors: [2]
  zustand-rules/no-state-mutation: [2]
  zustand-rules/enforce-use-setstate: [2]
  zustand-rules/enforce-state-before-actions: [2]
  zustand-rules/enforce-slices-when-large-state: [0]
```

eslint fails to find some of the rules:

```
  1:1  error  Definition for rule 'zustand-rules/use-store-selectors' was not found           zustand-rules/use-store-selectors
  1:1  error  Definition for rule 'zustand-rules/no-state-mutation' was not found             zustand-rules/no-state-mutation
  1:1  error  Definition for rule 'zustand-rules/enforce-use-setstate' was not found          zustand-rules/enforce-use-setstate
  1:1  error  Definition for rule 'zustand-rules/enforce-state-before-actions' was not found  zustand-rules/enforce-state-before-actions
```
